class AppTokenResponse {
  String appToken; //token generated by backend
  int id; //user id in db

  AppTokenResponse({required this.appToken, required this.id});

  factory AppTokenResponse.fromJson(Map<String, dynamic> json) =>
      AppTokenResponse(
        appToken: json['custom_token'],
        id: json['id'],
      );
}
